remote_theme: just-the-docs/just-the-docs

# Site settings
title: Modular CSS Layout
description: Modular CSS Layout for Obsidian
baseurl: "/obsidian-modular-css-layout" # the subpath of your site, e.g. /blog
url: "https://efemkay.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

# Site Logo -- i don't have one (yet)
# Site Search -- I maintained the default (which is enabled with some others like depth and so on

# Mermaid diagrams -- I include this because it's an opt-in
mermaid:
  version: "9.1.6"   # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/

# Aux links for the upper right navigation
aux_links:
  "MCL on GitHub":
    - "//github.com/efemkay/obsidian-modular-css-layout"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark
